knowellG/fcc-roguelike-dungeon-crawler

- src/App.js
Added folders to src and added a test component.
> add test component

- src/components/TestComponent.js
Added a components folder and a test component. For real this time.
> really add the test component

- src/components/Tiles.js
- src/containers/MapGenerator.js
Just added the "return" to statements in map() callbacks in render();
> adds returns to map callbacks in render

- public/index.html
- src/components/App.js
- src/components/Tiles.js
- src/containers/MapGenerator.js
- src/index.js
- src/reducers/index.js
- src/reducers/reducers_map.js
- src/reducers/reducers_mapGenerator.js
- src/stylesheets/styles.css
Added a simple map-generator function to render the SVG elements.
Merge with the master branch
> Map generator

- src/containers/MapGenerator.js
- src/reducers/reducers_mapGenerator.js
Changed the format of initialState, as well added occupiedCoordinates to keep track of Map Generator first
> Occupied coordinate placement

- src/reducers/reducers_mapGenerator.js
Function `placeEnemies` takes `initalState.grid` and a `numberOfEnemies`, adds enemy positions to `initialState.occupiedCoordinates`, and adds enemy objects to` initialState.enemies`.
> Place enemy

- src/reducers/reducers_mapGenerator.js
fixed initialState.occupiedCoords
> placeEnemies() updates occupiedCoords

- src/containers/MapGenerator.js
- src/reducers/reducers_mapGenerator.js
Added `placeWeapons` function in the `reducers_mapGeneration` to initialize the weapons objects and place each weapons around the map where it is available based on `initialState.occupiedCoordinates`
> Place weapons

- src/reducers/reducers_mapGenerator.js
Added `placeItems` function for placing items across the map for `initialState`
> added placeItems function

- src/components/Tiles.js
- src/reducers/reducers_mapGenerator.js
todo: change grid state and add out of bounds / wall logic
> changes player state on move and fixes tile row/col issue

- src/components/App.js
- src/containers/MapGenerator.js
- src/reducers/initialState.js
- src/reducers/reducers_mapGenerator.js
- src/stylesheets/styles.css
merges wall interaction and viewbox
> Svg viewbox

- src/reducers/initialState.js
- src/reducers/reducers_mapGenerator.js
Player can go over items, weapons and enemies in the map. Walls are blocked
> player can go over grids except wall

- src/reducers/reducers_mapGenerator.js
Player's weapon property is updated when picking up a weapon in the map
> player updates its weapon property when weapon is picked up

- src/actions/index.js
- src/components/App.js
- src/components/Tiles.js
- src/containers/MapGenerator.js
- src/reducers/initialState.js
- src/reducers/reducers_mapGenerator.js
addresses warnings and removes irrelevant old code for rendering items
> cleans up several console warnings

- src/reducers/initialState.js
- src/reducers/reducers_mapGenerator.js
Updating the enemies' state is now immutable
> debating if its immutable or not

- src/reducers/reducers_mapGenerator.js
updates player.attack based on weapon and player.level and randomizes attack strength when fighting
> Player attack strength

- src/reducers/initialState.js
- src/reducers/reducers_mapGenerator.js
After defeating an enemy player's state updates as so:
- EXP points 
- Level Up when EXP points is met
- When leveling up, player's attack increases 5 points
> Exchange exp points

- src/preload/initialState.js
- src/reducers/reducers_mapGenerator.js
When player is killed by enemy, it will re-initialized the game and re-spawn everything
> Re initializing game

- src/actions/index.js
- src/components/App.js
- src/components/Tiles.js
- src/containers/MapGenerator.js
- src/containers/ToggleLights.js
- src/preload/gameObjects.js
- src/preload/initialState.js
- src/reducers/index.js
- src/reducers/reducers_mapGenerator.js
- src/reducers/reducers_toggleLights.js
- src/stylesheets/styles.css
Toggle Lights is fully functional - user can toggle the lights
> Toggle lights

- src/components/Tiles.js
- src/containers/MapGenerator.js
- src/preload/gameObjects.js
- src/preload/initialState.js
- src/reducers/reducers_mapGenerator.js
- src/reducers/reducers_toggleLights.js
- src/stylesheets/styles.css
Boss is now part of the game. 
- Boss is placed only at the last level of the dungeon
- Reducer handles 3 case scenarios with interaction of the boss
1. Case 1: if player kills the boss -> restart the game
2. Case 2: if player dies against the boss -> restart the game
3. Case 3: if player and boss are still alive after battle -> update their new damaged health
> Boss placement

- src/components/App.js
- src/components/MessageBoard.js
- src/containers/MapGenerator.js
- src/containers/MessageContainer.js
- src/containers/StatusBarContainer.js
- src/preload/initialState.js
- src/reducers/reducers_mapGenerator.js
- src/stylesheets/styles.css
Dialogue window is prompted whenever the player interacts with enemy, items, weapons and dungeon levels
> Dialogue window

- src/preload/generator.js
- src/preload/initialState.js
- src/reducers/helpers.js
Added [Flood-fill](https://en.wikipedia.org/wiki/Flood_fill) algorithm inside `Dungeon` function constructor to avoid any dungeons that render disconnected from the rest
> Map generator 2

- src/components/Tiles.js
- src/containers/MapGenerator.js
- src/preload/generator.js
- src/preload/initialState.js
- src/reducers/helpers.js
Updated the initial and pre-loader setup including
-map grid is 45 x 45 (before 30 x 30)
-changed the size of tiles to 40 pxl x 40 pxl to have 25 tiles by 25 tiles rendered within the SVG canvas (before it was set 50 x 50 pxl to have 20 tiles by 20 tiles
-updated number of random rooms it will generate
-updated the min/max size of rooms
> Pre loader setup

- src/containers/MapGenerator.js
- src/reducers/reducers_toggleLights.js
I've increased the peripheral view for the player when light-toggle is on
> increased periphals view for the player

- config/env.js
- config/jest/CSSStub.js
- config/jest/FileStub.js
- config/paths.js
- config/polyfills.js
- config/webpack.config.dev.js
- config/webpack.config.prod.js
- package.json
- scripts/build.js
- scripts/start.js
- scripts/test.js
- src/components/App.js
- src/stylesheets/styles.css
- src/stylesheets/styles.scss
Ejects from create-react-app happy land.
Adds scss loader
includes toggle lights update
scss styles
changed some of the colors on the map
- player is gold
- goal is white
- boss is dark red
> Eject add sass

- src/preload/gameObjects.js
- src/preload/generator.js
- src/preload/initialState.js
updated the size of map, as well as the numbers of rooms and its max/min size
> Improve game experience
